### ISSUE TITLE
do we care about length of series?

### ISSUE THREAD

**Issue by ConchuOD** [ConchuOD/nipa#11]
We still have the netdev 15 patch per series thing. Do we want that?
https://patchwork.kernel.org/project/linux-riscv/patch/20230113171026.582290-2-david@redhat.com/

@bjoto

**Comment by bjoto** [comment]
I guess it's really up you and @palmer-dabbelt ! Personally, I think it's a good guideline, but maybe a warning is better?

**Comment by ConchuOD** [comment]
tbh, I'd rather see something like the jh7110/visionfive2 base support come in as one patchset containing pinctrl, clock driver, bindings and dt.
Even if that is 30 patches, it is a lot easier to keep the "big picture" in mind - although I would probably not say the same about people sending 20 patch patchsets for alternative stuff....

**Comment by bjoto** [comment]
Ok! Let's disable that check!

Completely untested: https://github.com/bjoto/nipa/commit/44669393bf0bff2d50066ef3fa8d57b9c2526c05 I hope `"disabled"` work for series as well.

**Comment by ConchuOD** [comment]
I'd also be tempted to edit the cover letter test to make no cover letter on a series an error rather than a warning

**Comment by bjoto** [comment]
Oh, I thought that it was an error on series longer than 2 patches. Less, just a warning. If not, I'm definitely in the "error rather than warning" camp!

**Comment by ConchuOD** [comment]
> Oh, I thought that it was an error on series longer than 2 patches. Less, just a warning. If not, I'm definitely in the "error rather than warning" camp!

It returns 250, which is a warning iirc

**Comment by bjoto** [comment]
Ah, yes. Yeah, error is better for the "presence of a cover letter" test.
